# Generated by Django 3.0.8 on 2021-08-13 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the menu will be available.', verbose_name='availability date')),
                ('name', models.TextField(default='Menu for today', help_text='Descriptive name.', max_length=80)),
                ('is_enabled', models.BooleanField(default=True, help_text='menu status, to check availability', verbose_name='Is enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-availability_date'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Description of the elements of the dish.')),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True, help_text='To distinguish the available dishes.', verbose_name='Is enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
