# Generated by Django 3.0.8 on 2021-08-18 03:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu',
        ),
        migrations.CreateModel(
            name='DishMenu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'unique_together': {('menu', 'dish')},
            },
        ),
    ]
