# Generated by Django 3.0.8 on 2021-08-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20210818_0339'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.DishMenu'),
        ),
    ]
